name: Build and Publish

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew buildAll

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: libs/

      - name: Publish to GitHub Packages
        if: github.event_name == 'push'
        run: ./gradlew publishToGitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
